### PR TITLE
Fix python-slugify pins

### PR DESCRIPTION
**Pull request by xylar**
Add xylar as a maintainer

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@sodre, I looked upstream at `master` (there seems to be no tag for 0.15.0) and there's no upper bound on `python-slugify`.  This is important because the current version is 4.x.x and `airflow` requires a version above `3.0.0`.  Let me know if you disagree, though.

**Comment by sodre** [comment]
Hi @xylar 

It looks 0.15.0 is only on PyPi. 

With that being said, I'm happy to take your update.

**Comment by xylar** [comment]
> It looks 0.15.0 is only on PyPi.

Right, I seems like upstream switched to just putting releases on PyPi without making tags, which isn't good.  But also not really anything we can do anything about.

Thanks for merging!

**Pull request merged**
